name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: Inspect base image entrypoint
        run: |
          docker pull docker.io/vastai/kvm:ubuntu_desktop_22.04-2025-11-21
          echo "=== ENTRYPOINT/CMD оригинального образа ==="
          docker inspect docker.io/vastai/kvm:ubuntu_desktop_22.04-2025-11-21 --format='ENTRYPOINT={{.Config.Entrypoint}} CMD={{.Config.Cmd}}'

  build:
    needs: inspect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: wetfoxx
          password: dckr_pat_DARpcb-Tp_HUaBL-R-c71jgLG_8
